name: 'PHPUnit Runner'
run-name: Run PHPUnit tests
on: [push]
jobs:
  guzzle7-php81:
    runs-on: ubuntu-latest
    container:
      image: kamermans/composer:php8.1
    steps:
      - name: Composer install
        run: composer install && vendor/bin/phpunit -vvvv
      - name: PHPUnit
        run: vendor/bin/phpunit -vvvv
